controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  - name: fake_arm_body_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_0
      - joint_1
      - joint_2
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_3
      - joint_4
initial:  # Define initial robot poses per group
  - group: arm
    pose: default